import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { api, post } from "../lib/api";
import { Card, Btn, Verdict } from "./ui";
const pct=(x:number)=>`${(x*100).toFixed(2)}%`;
export default function Accountability(){
 const q=useQuery({queryKey:["accountability"],queryFn:()=>api("/accountability"),retry:false});
 const qc=useQueryClient();const[selected,setSelected]=useState<number|null>(null);const[category,setCategory]=useState("unknown");const[evidence,setEvidence]=useState("");const[lesson,setLesson]=useState("");
 const save=useMutation({mutationFn:()=>post(`/verdicts/${selected}/review`,{category,evidence,lesson}),onSuccess:()=>{qc.invalidateQueries({queryKey:["accountability"]});setEvidence("");setLesson("");}});
 if(q.isError)return <Card title="Review unavailable"><p role="alert">{String(q.error)}</p></Card>;
 if(!q.data)return <Card title="Loading saved verdict reviews…"><p>Loading saved evidence.</p></Card>;
 const d=q.data;const call=d.calls.find((v:any)=>v.id===selected);
 return <>
 <Card title="Verdict post-mortems"><p className="text-sm text-neutral-600">A missed direction is measurable. Why it missed needs evidence, not hindsight. Categories are your review hypotheses, never automatic blame.</p>
 {!d.calls.length&&<div className="empty-state"><b>No saved calls to review yet</b><p>Run a real discussion and wait for an observed horizon. No invented misses or causes.</p></div>}
 <div className="grid gap-3 mt-4">{d.calls.map((v:any)=><button key={v.id} className="review-call" onClick={()=>{setSelected(v.id);setCategory(v.review.category||"unknown");setEvidence(v.review.evidence||"");setLesson(v.review.lesson||"");save.reset();}}><b>{v.symbol} · call #{v.id}</b><span className="ml-3"><Verdict v={v.verdict}/></span><p className="text-sm">{v.timestamp} · {v.status}</p><p className="text-sm">{v.scored_horizons.map((h:any)=>`${h.horizon}-session: ${h.result}`).join(" / ")||"Waiting for observed outcomes"}</p><p className="text-xs">Cause: {v.review.category||"unknown"}{v.review.category?" (reviewer hypothesis)":""} · Open audit ↗</p></button>)}</div></Card>
 {call&&<Card title={`${call.symbol} / audit drill-down`}><p>{call.reasoning||"No saved reasoning."}</p><div className="overflow-x-auto"><table className="w-full mt-3 text-sm text-left"><thead><tr><th>Horizon/result</th><th>Observed closes</th><th>Stock</th><th>Nifty</th></tr></thead><tbody>{call.scored_horizons.map((h:any)=><tr key={h.horizon}><td>{h.horizon} sessions · {h.result}</td><td>{h.start_date}: {h.start_close} → {h.end_date}: {h.end_close}</td><td>{pct(h.stock_return)}</td><td>{pct(h.benchmark_return)}</td></tr>)}</tbody></table></div>
 <h3 className="font-bold mt-4">What can we actually establish?</h3><ul className="list-disc pl-5 text-sm">{call.evidence_gaps.map((g:string)=><li key={g}>{g}</li>)}</ul><details className="mt-3"><summary>Saved input snapshot and source</summary><pre className="mt-2 text-xs overflow-auto">{JSON.stringify(call.audit,null,2)}</pre></details><details className="mt-3"><summary>Saved role arguments ({call.positions.length})</summary>{call.positions.map((p:any,i:number)=><div key={i} className="data-card mt-2"><b>{p.agent_name} · {p.model||"model not recorded"}</b><p className="text-sm">{p.argument}</p><pre className="text-xs overflow-auto">{JSON.stringify(p.evidence||[],null,2)}</pre></div>)}</details>
 <form className="mt-5 space-y-3" onSubmit={e=>{e.preventDefault();save.mutate();}}><h3 className="font-bold">Your evidence-led review</h3><p className="text-xs text-neutral-600">Shared engine-key access. No personal information. Stored on ephemeral free Render disk. Saving a review never changes prompts or trading settings.</p><label className="block">Possible cause<select aria-label="Possible cause" className="block w-full" value={category} onChange={e=>setCategory(e.target.value)}>{["unknown","bad_data","weak_debate","wrong_assumption","market_change"].map(c=><option key={c} value={c}>{c.split("_").join(" ")}</option>)}</select></label><label className="block">Evidence and source reference<textarea className="block w-full" required minLength={10} maxLength={2000} value={evidence} onChange={e=>setEvidence(e.target.value)} placeholder="What saved input or external observation supports this hypothesis?"/></label><label className="block">Lesson or next test<textarea className="block w-full" maxLength={1000} value={lesson} onChange={e=>setLesson(e.target.value)}/></label><Btn disabled={save.isPending||evidence.trim().length<10}>Save review hypothesis</Btn>{save.isError&&<p role="alert">{String(save.error)}</p>}{save.isSuccess&&<p role="status">Review saved. No model configuration changed.</p>}</form></Card>}
 <Card title="Self-healing desk / suggestions only"><p className="text-sm">One five-session sample per verdict. We need at least5 calls and3 misses (60%+) in a role/regime group before suggesting a review. These are jury outcomes the role participated in, not that agent's isolated accuracy.</p>{!d.suggestions.length&&<div className="empty-state"><b>Not enough repeated evidence for a suggestion</b><p>No automatic prompt or threshold changes. More observed outcomes are needed.</p></div>}{d.suggestions.map((s:any)=><div className="data-card mt-3" key={s.id}><b>{s.role} · {s.regime}</b><p>{s.misses}/{s.n} five-session directional misses. Calls: {s.verdict_ids.join(", ")}</p><p className="mt-2">{s.proposal}</p><p className="text-xs mt-2">{s.note} Review these calls, then choose a separate prompt/threshold experiment for approval. Nothing auto-applies.</p></div>)}</Card>
 </>;
}
